POST http://localhost:3000/word
Content-Type: application/json

{
      "partOfSpeech": "n",
      "definition": ["gavri def"],
      "word": "TheWord",
      "firstLetter": "theFirstLetter"
}

###

GET http://localhost:3000/word/TheWord

###

GET http://localhost:3000/word/Dog/n

###

GET http://localhost:3000/partOfSpeech/n?letter=Z


### 

GET http://localhost:3000/setup

###

GET http://localhost:3000/


### -----------------------------------------------------------


GET https://v8pauve0t1.execute-api.us-east-1.amazonaws.com/word/Book

###

GET https://v8pauve0t1.execute-api.us-east-1.amazonaws.com/word/Zany/v

###

GET https://v8pauve0t1.execute-api.us-east-1.amazonaws.com/partOfSpeech/v

###

GET https://v8pauve0t1.execute-api.us-east-1.amazonaws.com/partOfSpeech/n?letter=N

